# Default values for cobol.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1


imagerepository: "svidrascu/devcon:latest"
image:
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  applicationBasePath: ./
  path: /development
  tls: []
